### ISSUE TITLE
apt_pkg.Error: E:Archive is too short

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#101]
This happens when signature file is generated with the `--generate-changelog` option. Seems to happen only on some packages.

Wild guess is that this might be happening for new package dependencies that are pulled in, which will not have any changelog delta to show. But this is just a **guess**

```
Downloading smplayer - 1 MiB                                                             
Downloading vokoscreen - 1 MiB                                                             
python3-xdg found in cache                                                            
libwireshark12 done                                                             
vokoscreen done                                                             
sonnet-plugins found in cache                                                            
Exception in thread Thread-1:###################] 100.0% of 22 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 694, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1295, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1120, in buildChangelog
    pkgHandle = DebPackage(pkgPath)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 77, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 87, in open
    self._debfile = apt_inst.DebFile(self.filename)
apt_pkg.Error: E:Archive is too short

smplayer done                                                             
Downloading wireshark-qt - 3 MiB                                                             
Downloading wireshark-common - 430 KiB                                                             
Downloading wireshark - 45 KiB                                                             
```

**Comment by rickysarraf** [comment]
This is a nasty problem. Because, the download is supposed to be huge. The payload is downloaded but because we run into this exception, the payload gets discarded.

Things to check:
* Is the payload corrupt, thus resulting in the exception ?
* Or is the exception non-fatal and could be handled and ignored ?


```
rrs@lenovo:/var/tmp/apt-offline (master)$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
The following packages were automatically installed and are no longer required:
The following packages have been kept back:
  gcc-10-base gcc-10-base:i386 libatomic1 libatomic1:i386 libcc1-0 libgcc-s1 libgcc-s1:i386 libgfortran5 libgomp1 libitm1 liblsan0 libquadmath0
  libstdc++6 libstdc++6:i386 libtsan0 libubsan1
The following packages will be upgraded:
  adb android-libadb android-libbacktrace android-libbase android-libcrypto-utils android-libcutils android-liblog android-libsparse
  android-libunwind android-libutils android-libziparchive appstream apt apt-config-icons apt-utils binutils binutils-common
  binutils-x86-64-linux-gnu bison bsdutils cdebconf cpp-9 debhelper deborphan dicod docker-doc docker.io eject encfs fastboot fdisk file
  fontconfig fontconfig-config g++-9 gcc-9 gcc-9-base gcc-9-base:i386 id-utils idle3-tools intel-microcode iso-codes kgpg libappstream4
  libappstreamqt2 libapt-pkg6.0 libasan5 libbinutils libblkid1 libboost-filesystem1.67.0 libboost-iostreams1.67.0 libboost-regex1.67.0
  libboost-system1.67.0 libc-bin libc-dev-bin libc-l10n libc6 libc6:i386 libc6-dbg libc6-dev libcap2 libcap2-bin libclass-xsaccessor-perl
  libctf-nobfd0 libctf0 libdebconfclient0 libdebhelper-perl libdico2 libdns-export1110 libexif12 libexporter-tiny-perl libfdisk1
  libfile-desktopentry-perl libfontconfig1 libgcc-9-dev libgd3 libgps26 libhttp-message-perl libibus-1.0-5 libisc-export1105
  libjson-maybexs-perl liblilv-0-0 libmagic-mgc libmagic1 libmount1 libnm0 libnss-mymachines libnss-systemd libopenconnect5 libopencsd0
  libpam-cap libpam-systemd libperl5.30 libpod-constants-perl libprocps8 libpython3.8 libpython3.8-minimal libpython3.8-stdlib
  libqt5webenginecore5 libqt5webenginewidgets5 libquazip5-1 libre-engine-re2-perl libregexp-pattern-license-perl librsvg2-2 librsvg2-common
  libruby2.7 libsmartcols1 libsrt1 libstdc++-9-dev libsystemd0 libsystemd0:i386 libtext-glob-perl libtimedate-perl libtype-tiny-xs-perl libudev1
  libudisks2-0 libunbound8 libupower-glib3 libuuid1 libyaml-cpp0.6 licensecheck lintian locales mount network-manager perl perl-base
  perl-modules-5.30 perl-openssl-defaults powerstat procps python-pkg-resources python-setuptools python3-appdirs python3-docker
  python3-httplib2 python3-pycryptodome python3-tz python3-yaml python3.8 python3.8-minimal qemu-kvm qemu-system-arm qemu-system-common
  qemu-system-data qemu-system-gui qemu-system-misc qemu-system-ppc qemu-system-sparc qemu-system-x86 qemu-utils rfkill ruby2.7 sudo systemd
  vim-common vim-runtime vim-tiny wpasupplicant xxd youtube-dl
173 upgraded, 2 newly installed, 0 to remove and 16 not upgraded.
Need to get 304 MB of archives.
After this operation, 18.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
21:50 ♒♒♒    ☹ 😟=> 130  
rrs@lenovo:/var/tmp/apt-offline (master)$ rm -f /tmp/upgrade.zip ; ./apt-offline get /tmp/upgrade.uris --bundle /tmp/upgrade.zip --proxy-host chutzpah --proxy-port 3142 --threads 5

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

Downloading bsdutils - 142 KiB                                                             
Downloading libperl5.30 - 3 MiB                                                             
Downloading libclass-xsaccessor-perl - 37 KiB                                                             
Downloading perl-modules-5.30 - 2 MiB                                                             
Downloading perl - 283 KiB                                                             
libclass-xsaccessor-perl done                                                             
Downloading perl-base - 1 MiB                                                             
bsdutils done                                                             
perl done                                                             
Downloading gcc-10-base - 192 KiB                                                             
Downloading gcc-10-base - 192 KiB                                                             
perl-modules-5.30 done                                                             
libperl5.30 done                                                             
gcc-10-base done                                                             
gcc-10-base done                                                             
perl-base done                                                             
Downloading libstdc++6 - 514 KiB                                                             
Downloading libstdc++6 - 480 KiB                                                             
Downloading libgcc-s1 - 40 KiB                                                             

Downloading libgcc-s1 - 48 KiB                                                             
libgcc-s1 done                                                             
libgcc-s1 done                                                             
Downloading libatomic1 - 9 KiB                                                             
Downloading libatomic1 - 8 KiB                                                             
Downloading libubsan1 - 130 KiB                                                             
libatomic1 done                                                             
Downloading libtsan0 - 305 KiB                                                             
Downloading libquadmath0 - 141 KiB                                                             
libstdc++6 done                                                             
libubsan1 done                                                             
libstdc++6 done                                                             
Downloading liblsan0 - 137 KiB                                                             
libquadmath0 done                                                             
libtsan0 done                                                             
Downloading libitm1 - 25 KiB                                                             
libitm1 done                                                             
liblsan0 done                                                             
Downloading libgomp1 - 96 KiB                                                             
Downloading libgfortran5 - 710 KiB                                                             
libgomp1 done                                                             
Downloading libcc1-0 - 38 KiB                                                             
Downloading libc-dev-bin - 274 KiB                                                             
Downloading libc6-dev - 2 MiB                                                             
Downloading libc6-dbg - 10 MiB                                                             
Downloading libc6 - 2 MiB                                                             
Downloading libc6 - 2 MiB                                                             
Downloading libblkid1 - 187 KiB                                                             
libc6 done                                                             
Exception in thread Thread-2:#############      ]  78.8% of 30 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 870, in runf 30 MiB
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
libc6-dev done                                                             
    pkgHandle = DebPackage(pkgPath)#######      ]  79.1% of 30 MiB
    self.open(filename)###################      ]  79.1% of 30 MiB
    self._debfile = apt_inst.DebFile(self.filename)79.2% of 30 MiB
libblkid1 done                                                             
Downloading libfdisk1 - 226 KiB                                                             
libfdisk1 done                                                             
Downloading libmount1 - 203 KiB                                                             
libmount1 done                                                             
libc6-dbg done                                                             
Exception in thread Thread-5:###################] 100.0% of 31 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
Downloading libsmartcols1 - 151 KiB                                                             
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1123, in buildChangelog
    pkgHandle = DebPackage(pkgPath)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 65, in __init__
    self.open(filename)
    self._debfile = apt_inst.DebFile(self.filename)
libsmartcols1 done                                                             
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineLib.py", line 696, in run
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1123, in buildChangelog
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 65, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 75, in open
    self._debfile = apt_inst.DebFile(self.filename)
apt_pkg.Error: E:Archive is too short
Downloading fdisk - 180 KiB                                                             
Downloading util-linux - 1 MiB                                                             
fdisk done                                                             
Downloading libudev1 - 163 KiB                                                             
Downloading udev - 1 MiB                                                             
Downloading systemd-timesyncd - 121 KiB                                                             
Downloading systemd-coredump - 136 KiB                                                             
util-linux done                                                             
Exception in thread Thread-4:###################] 100.0% of 34 MiB
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1123, in buildChangelog
Downloading libnss-mymachines - 221 KiB                                                             
    pkgHandle = DebPackage(pkgPath)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 65, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 75, in open
    self._debfile = apt_inst.DebFile(self.filename)
apt_pkg.Error: E:Archive is too short
libnss-mymachines done                                                             
Downloading systemd-container - 403 KiB                                                             
systemd-container done                                                             
Downloading libpam-systemd - 274 KiB                                                             
libpam-systemd done                                                             
Downloading systemd - 3 MiB                                                             
systemd done                                                             
Exception in thread Thread-1:###################] 100.0% of 39 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/var/tmp/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1123, in buildChangelog
    pkgHandle = DebPackage(pkgPath)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 65, in __init__
    self.open(filename)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 75, in open
    self._debfile = apt_inst.DebFile(self.filename)
apt_pkg.Error: E:Archive is too short

Downloaded data to /tmp/upgrade.zip
21:51 ♒♒♒   ☺ 😄    
rrs@lenovo:/var/tmp/apt-offline (master)$  ls -lh /tmp/upgrade.zip 
-rw-r--r-- 1 rrs rrs 25M May 25 21:51 /tmp/upgrade.zip
21:51 ♒♒♒   ☺ 😄    
rrs@lenovo:/var/tmp/apt-offline (master)$ 

```

**Comment by rickysarraf** [comment]
So the problem lies with the (bad) proxy and has nothing to do with `apt-offline`. When we access the same payload over `sshfs`, it is all fine. The proxy is already known to have issues during the `update` operation. In this example, it also proves to show that when downloading the .debs too, the proxy does not behave correct.

**So, there's nothing to do in this bug report.**

```
rrs@lenovo:/var/tmp/apt-offline (master)$ mkdir /var/tmp/foo
21:55 ♒♒♒   ☺ 😄    
rrs@lenovo:/var/tmp/apt-offline (master)$ sshfs chutzpah:/var/ /var/tmp/foo/
21:55 ♒♒♒   ☺ 😄    
rrs@lenovo:/var/tmp/apt-offline (master)$ rm -f /tmp/upgrade.zip ; ./apt-offline get /tmp/upgrade.uris --bundle /tmp/upgrade.zip --threads 5 --cache-dir /var/tmp/foo/cache/ | tee /tmp/apt-offline.log

Fetching APT Data
WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

perl found in cache                                                            
perl-modules-5.30 found in cache                                                            
libperl5.30 found in cache                                                            
libclass-xsaccessor-perl found in cache                                                            
gcc-10-base found in cache                                                            
gcc-10-base found in cache                                                            
libstdc++6 found in cache                                                            
Downloading bsdutils - 142 KiB                                                             
WARN: Ignoring err ENOENT, multiarch package name clash /tmp/gcc-10-base.changelog

perl-base found in cache                                                            
bsdutils done                                                             
libatomic1 found in cache                                                            
libatomic1 found in cache                                                            
libgcc-s1 found in cache                                                            
libgcc-s1 found in cache                                                            
libstdc++6 found in cache                                                            
libubsan1 found in cache                                                            
libtsan0 found in cache                                                            
liblsan0 found in cache                                                            
libquadmath0 found in cache                                                            
libcc1-0 found in cache                                                            
libgomp1 found in cache                                                            
libgfortran5 found in cache                                                            
libc-dev-bin found in cache                                                            
libc6-dev found in cache                                                            
libc6 found in cache                                                            
libc6 found in cache                                                            
libc6-dbg found in cache                                                            
WARN: Ignoring err type Duplicate name: 'libc6.changelog'

libuuid1 found in cache                                                            
libblkid1 found in cache                                                            
libmount1 found in cache                                                            
fdisk found in cache                                                            
libsmartcols1 found in cache                                                            
libfdisk1 found in cache                                                            
util-linux found in cache                                                            
systemd-timesyncd found in cache                                                            
systemd-coredump found in cache                                                            
libudev1 found in cache                                                            
libnss-systemd found in cache                                                            
udev found in cache                                                            
libpam-systemd found in cache                                                            
libnss-mymachines found in cache                                                            
libsystemd0 found in cache                                                            
systemd-container found in cache                                                            
systemd found in cache                                                            
libapt-pkg6.0 found in cache                                                            
mount found in cache                                                            
systemd-sysv found in cache                                                            
libsystemd0 found in cache                                                            
WARN: Ignoring err type Duplicate name: 'libsystemd0.changelog'
libdico2 found in cache                                                            
dicod found in cache                                                            
Downloading libcap2 - 22 KiB                                                             
docker.io found in cache                                                            
libc-bin found in cache                                                            
libcap2 done                                                             
apt-utils found in cache                                                            
apt found in cache                                                            
libnm0 found in cache                                                            
network-manager found in cache                                                            
python3.8 found in cache                                                            
libpython3.8-stdlib found in cache                                                            
libpython3.8 found in cache                                                            
python3.8-minimal found in cache                                                            
Downloading cdebconf - 171 KiB                                                             
libdebconfclient0 found in cache                                                            
cdebconf done                                                             
libasan5 found in cache                                                            
Downloading wpasupplicant - 1 MiB                                                             
libpython3.8-minimal found in cache                                                            
uuid-runtime found in cache                                                            
wpasupplicant done                                                             
libctf0 found in cache                                                            
libstdc++-9-dev found in cache                                                            
libgcc-9-dev found in cache                                                            
gcc-9 found in cache                                                            
g++-9 found in cache                                                            
libctf-nobfd0 found in cache                                                            
binutils found in cache                                                            
libbinutils found in cache                                                            
binutils-common found in cache                                                            
binutils-x86-64-linux-gnu found in cache                                                            
gcc-9-base found in cache                                                            
gcc-9-base found in cache                                                            
cpp-9 found in cache                                                            
WARN: Ignoring err type Duplicate name: 'gcc-9-base.changelog'

Downloading procps - 256 KiB                                                             
Downloading libprocps8 - 61 KiB                                                             
Downloading vim - 1 MiB                                                             
Downloading vim-tiny - 669 KiB                                                             
Downloading vim-runtime - 5 MiB                                                             
vim done                                                             
libprocps8 done                                                             
vim-tiny done                                                             
vim-runtime done                                                             
Downloading vim-common - 187 KiB                                                             
Downloading libmagic1 - 117 KiB                                                             
Downloading libmagic-mgc - 255 KiB                                                             
Downloading xxd - 152 KiB                                                             
xxd done                                                             
vim-common done                                                             
file done                                                             
libmagic-mgc done                                                             
libmagic1 done                                                             
libc-l10n found in cache                                                            
locales found in cache                                                            
Downloading adb - 94 KiB                                                             
Downloading android-libadb - 130 KiB                                                             
Downloading android-libcutils - 31 KiB                                                             
Downloading android-liblog - 43 KiB                                                             
Downloading android-libbase - 31 KiB                                                             
android-libbase done                                                             
android-liblog done                                                             
android-libunwind found in cache                                                            
Downloading android-libcrypto-utils - 10 KiB                                                             
Downloading android-libutils - 57 KiB                                                             
Downloading android-libbacktrace - 53 KiB                                                             
Downloading android-libsparse - 25 KiB                                                             
android-libcrypto-utils done                                                             
android-libbacktrace done                                                             
android-libutils done                                                             
android-libsparse done                                                             
Downloading android-libziparchive - 32 KiB                                                             
android-libziparchive done                                                             
libappstream4 found in cache                                                            
libdebhelper-perl found in cache                                                            
debhelper found in cache                                                            
docker-doc found in cache                                                            
deborphan found in cache                                                            
Downloading apt-config-icons - 8 KiB                                                             
Downloading bison - 998 KiB                                                             
Downloading appstream - 188 KiB                                                             
apt-config-icons done                                                             
appstream done                                                             
bison done                                                             
libtinyxml2-8 found in cache                                                            
encfs found in cache                                                            
eject found in cache                                                            
libfontconfig1 found in cache                                                            
fontconfig-config found in cache                                                            
intel-microcode found in cache                                                            
id-utils found in cache                                                            
iso-codes found in cache                                                            
Downloading fastboot - 66 KiB                                                             
libappstreamqt2 found in cache                                                            
libboost-filesystem1.67.0 found in cache                                                            
libboost-system1.67.0 found in cache                                                            
fontconfig found in cache                                                            
libboost-iostreams1.67.0 found in cache                                                            
libboost-regex1.67.0 found in cache                                                            
Downloading idle3-tools - 11 KiB                                                             
Downloading kgpg - 2 MiB                                                             
idle3-tools done                                                             
kgpg done                                                             
libexif12 found in cache                                                            
Downloading libpam-cap - 14 KiB                                                             
Downloading libisc-export1105 - 390 KiB                                                             
Downloading libcap2-bin - 33 KiB                                                             
libisc-export1105 done                                                             
libcap2-bin done                                                             
libexporter-tiny-perl found in cache                                                            
libpam-cap done                                                             
libgd3 found in cache                                                            
libfile-desktopentry-perl found in cache                                                            
libibus-1.0-5 found in cache                                                            
libjson-maybexs-perl found in cache                                                            
libgps26 found in cache                                                            
libhttp-message-perl found in cache                                                            
libopenconnect5 found in cache                                                            
Downloading libdns-export1110 - 969 KiB                                                             
libpod-constants-perl found in cache                                                            
libopencsd0 found in cache                                                            
libqt5webenginewidgets5 found in cache                                                            
liblilv-0-0 found in cache                                                            
libqt5webenginecore5 found in cache                                                            
libdns-export1110 done                                                             
libre2-7 found in cache                                                            
libregexp-pattern-license-perl found in cache                                                            
librsvg2-common found in cache                                                            
libre-engine-re2-perl found in cache                                                            
librsvg2-2 found in cache                                                            
Downloading libquazip5-1 - 81 KiB                                                             
libtext-glob-perl found in cache                                                            
libtimedate-perl found in cache                                                            
libquazip5-1 done                                                             
libruby2.7 found in cache                                                            
libsrt1 found in cache                                                            
libtype-tiny-xs-perl found in cache                                                            
libupower-glib3 found in cache                                                            
libudisks2-0 found in cache                                                            
licensecheck found in cache                                                            
powerstat found in cache                                                            
perl-openssl-defaults found in cache                                                            
lintian found in cache                                                            
Downloading libyaml-cpp0.6 - 121 KiB                                                             
libyaml-cpp0.6 done                                                             
libunbound8 done                                                             
python3-docker found in cache                                                            
python-setuptools found in cache                                                            
python-pkg-resources found in cache                                                            
python3-appdirs found in cache                                                            
python3-yaml found in cache                                                            
python3-tz found in cache                                                            
python3-pycryptodome found in cache                                                            
Downloading qemu-utils - 1011 KiB                                                             
Downloading qemu-system-common - 1 MiB                                                             
qemu-system-common done                                                             
Downloading qemu-system-data - 1 MiB                                                             
Downloading qemu-kvm - 72 KiB                                                             
Downloading qemu-system-x86 - 7 MiB                                                             
qemu-system-data done                                                             
Downloading qemu-system-arm - 6 MiB                                                             
qemu-system-arm done                                                             
Downloading qemu-system-gui - 99 KiB                                                             
Downloading qemu-system-misc - 30 MiB                                                             
qemu-system-gui done                                                             
rfkill found in cache                                                            
Downloading qemu-system-ppc - 6 MiB                                                             
Downloading qemu-system-sparc - 4 MiB                                                             
ruby2.7 found in cache                                                            
sudo found in cache                                                            
qemu-system-sparc done                                                             
qemu-system-ppc done                                                             
qemu-system-misc done                                                             
thermald found in cache                                                            
youtube-dl found in cache                                                            
util-linux-locales found in cache                                                            
upower found in cache                                                            
udisks2 found in cache                                                            
183 / 191 items: [##############################] 100.0% of 283 MiB
Downloaded data to /tmp/upgrade.zip
ERROR: Some items failed to download. Downloaded data may be incomplete
ERROR: Please run in verbose mode to see details about failed items
```
