### ISSUE TITLE
Proxy log formatting error (easy to fix)

### ISSUE THREAD

**Issue by aptsurfer** [rickysarraf/apt-offline#129]
When trying to specify proxy settings in the apt-offline GUI, this traceback appears:

```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apt_offline_gui/AptOfflineQtFetch.py", line 40, in run

apt_offline_core.AptOfflineCoreLib.fetcher(self.args)

File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 916, in fetcher

log.verbose("Proxy successfully set up with Host %s and port %d\n" % (Str_ProxyHost, Str_ProxyPort))

TypeError
:
%d format: a number is required, not str
```

Just swap that %d out with a %s to fix it. A more thorough testing suite might help catch mistakes like this.

**Comment by rickysarraf** [comment]
Thank you for the bug report. It is now fixed.
