### ISSUE TITLE
Unknown url type: 27

### ISSUE THREAD

**Issue by kyp44** [rickysarraf/apt-offline#147]
When I try to use apt-offline I get the following exception:

```
Fetching APT Data

Downloading 27                                                             
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/whitmdj/apt-offline/apt_offline_core/AptOfflineLib.py", line 703, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/home/whitmdj/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1382, in DataFetcher
    if DownloadPackages(PackageName, pkgFileWithType) is False and guiTerminateSignal is False:
  File "/home/whitmdj/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1351, in DownloadPackages
    if FetcherInstance.download_from_web(PackageName, PackageFile, Str_DownloadDir):
  File "/home/whitmdj/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 724, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '27'
```

I've written some scripts to use apt-offline to update an offline system. Let me know if more details are needed on my setup or how I'm running `apt-offline`.

**Comment by rickysarraf** [comment]
Please re-run with the `--verbose` switch and share the output. Also, please share the content of the `signature file`.

**Comment by rickysarraf** [comment]
And my guess is that you may have hit the same issue like in this: https://github.com/rickysarraf/apt-offline/issues/146

**Comment by kyp44** [comment]
Yes, I just confirmed that it is that issue, noting that my signature file does have the security updates message at the top. Closing this issue.
