### ISSUE TITLE
Python ValueError

### ISSUE THREAD

**Issue by Nordal** [rickysarraf/apt-offline#154]
Hi there.

I'm facing an issue creating bundle zip file using the following command:
apt-offline get /path/to/sig/file.sig --bundle /path/to/folder/bundle.zip

The signature file is created using apt-offline set -- /path/to/folder/file.sig

If I don't specify any threads, the program will terminate with the following error, and the bundle zip file will not contain all updates.

```
Downloading 1
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1335, in DataFetcher
    if DownloadPackages(PackageName, pkgFileWithType) is False and guiTerminateSignal is False:
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1304, in DownloadPackages
    if FetcherInstance.download_from_web(PackageName, PackageFile, Str_DownloadDir):
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 709, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '1’Type something to get started
```
If I specify e.g. -t=5 I will get the error, but the program will continue, and it seems I will get a functional bundle pack.

Both offline and online server are running Ubuntu 20.04

**Comment by rickysarraf** [comment]
Yes. This is an Ubuntu problem from what we know so far. It was reported earlier this quarter from users running Ubuntu. See this commit 50267a68844b70cff4c8d422df7d760a2595a65b and this bug report: https://github.com/rickysarraf/apt-offline/issues/147

THis is currently fixed in master branch. I'll see if I can prepare a release this week.
