### ISSUE TITLE
ValueError: unknown url type

### ISSUE THREAD

**Issue by Cory-Watson** [rickysarraf/apt-offline#190]
```
apt-offline v1.8.2
Ubuntu 20.04.4 LTS
python v3.8.10
```

I'm getting a `ValueError` exception thrown when attempting to download packages with apt-offline. Looks like there is a potential bug when the URLs get parsed? I'll try to dig into the code when I get some free time.

```
foo@baz:~$ apt-offline get -d pkgs/ apt_offline_elk-dev_20220525_143556.sig --verbose
...
...
VERBOSE: Item before split is: 3 standard security updates

VERBOSE: Item after split is: 3 standard security updates

VERBOSE: Stripped item URL is: 3
VERBOSE: Stripped item FILE is: standard
VERBOSE: 3   s t a n d a r d   s e c u r i t y   u p d a t e s
 is malformed
VERBOSE: Stripped item SIZE is: 0
VERBOSE: Stripped item CHECKSUM is: updates
VERBOSE: Thread is Thread-1
Downloading 3
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1335, in DataFetcher
    if DownloadPackages(PackageName, pkgFileWithType) is False and guiTerminateSignal is False:
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1304, in DownloadPackages
    if FetcherInstance.download_from_web(PackageName, PackageFile, Str_DownloadDir):
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 709, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '3'
```

**Comment by rickysarraf** [comment]
I believe this is already fixed in the latest release of apt-offline.
Ubuntu may not have the latest version so you could try the deb package
from Debian, or install directly from this repository

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by Cory-Watson** [comment]
Confirmed

After installing version 1.8.4 this seems to be fixed.
