### ISSUE TITLE
UnboundLocalError: local variable 'checksum' referenced before assignment

### ISSUE THREAD

**Issue by leegengyu** [rickysarraf/apt-offline#195]
OS: `Ubuntu 18.04.6`
apt-offline Version: `1.8.1`

Command 1
`sudo apt-offline set update.sig --update`

Command 2
`sudo apt-offline get update.sig --bundle update.zip`

Error encountered after running Command 2:
```
Fetching APT Data

Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2211, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1135, in fetcher
    (ItemURL, ItemFile, ItemSize, ItemChecksum) = stripper(item)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 841, in stripper
    log.verbose("Stripped item CHECKSUM is: %s\n" % checksum)
UnboundLocalError: local variable 'checksum' referenced before assignment
```

Command 2 (verbose)
`sudo apt-offline get update.sig --bundle update.zip --verbose`

```
VERBOSE: Namespace(bundle_file='update.zip', cache_dir=None, deb_bugs=False, disable_md5check=False, download_dir=None, func=<function fetcher at 0x7ff4c4ff9400>, get='update.sig', num_of_threads=1, proxy_host=None, proxy_port=None, simulate=False, socket_timeout=30, verbose=True)
VERBOSE: Default timeout now is: 30.

Fetching APT Data

VERBOSE: Item is ["'https://download.docker.com/linux/ubuntu/dists/bionic/InRelease'", 'download.docker.com_linux_ubuntu_dists_bionic_InRelease', '0\n']
VERBOSE: Stripped item URL is: https://download.docker.com/linux/ubuntu/dists/bionic/InRelease
VERBOSE: Stripped item FILE is: download.docker.com_linux_ubuntu_dists_bionic_InRelease
VERBOSE: Stripped item SIZE is: 0
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2211, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1135, in fetcher
    (ItemURL, ItemFile, ItemSize, ItemChecksum) = stripper(item)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 841, in stripper
    log.verbose("Stripped item CHECKSUM is: %s\n" % checksum)
UnboundLocalError: local variable 'checksum' referenced before assignment
```

I edited `update.sig` to contain only 1 line (for testing), and faced the same error above. This 1 line is: `'https://download.docker.com/linux/ubuntu/dists/bionic/InRelease' download.docker.com_linux_ubuntu_dists_bionic_InRelease 0`

**Comment by rickysarraf** [comment]
That is quite old a version. Can you please test it with the latest version from Debian Unstable ? It should install fine.

Checking the code for v1.8.1 it seems this issue has been redone and fixed already.

**Comment by leegengyu** [comment]
Thanks - I solved it by manually installing the latest Release version `1.8.5`.
