### ISSUE TITLE
Travis CI test failure

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#20]
ERROR: I couldn't understand file type icewm_1.3.7.orig.tar.gz.

ERROR: I couldn't understand file type icewm_1.3.7-1ubuntu1.debian.tar.gz.

ERROR: I couldn't understand file type eclipse_3.7.2-1.debian.tar.gz.

Traceback (most recent call last):

  File "./apt-offline", line 28, in <module>

    main()

  File "/home/travis/build/rickysarraf/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1997, in main

    args.func(args)

  File "/home/travis/build/rickysarraf/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1383, in installer

    magic_check_and_uncompress( archive_file, filename )

  File "/home/travis/build/rickysarraf/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1171, in magic_check_and_uncompress

    os.unlink(temp_filename)

OSError: [Errno 2] No such file or directory: '/tmp/apt-update-target-path-2422/eclipse_3.7.2.orig.tar.xzapt-offline'

The command "sudo ./tests/apt-offline-tests.sh 1>/dev/null" exited with 1.

Done. Your build exited with 1.

**Comment by rickysarraf** [comment]
This should be closed now, with today's commit 8c4335c54182d2791c26f43eb57b2b7867288d06
