### ISSUE TITLE
Multi-threading does not work for python 3.10

### ISSUE THREAD

**Issue by TomBlackwoodTTM** [rickysarraf/apt-offline#209]
Tried the multi-threading functionality `--threads 5` and my terminal returned the complaint:

```bash
Exception in thread Thread-1 (run):#############] 100.0% of 1 KiB
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 691, in run
    if threading.currentThread().guiTerminateSignal:
  File "/usr/lib/python3.10/threading.py", line 1449, in currentThread
    warnings.warn('currentThread() is deprecated, use current_thread() instead',
DeprecationWarning: currentThread() is deprecated, use current_thread() instead
```

**Comment by rickysarraf** [comment]
This is already fixed in one of the recent past releases. Please use the latest version. Also, when reporting an issue, please provide complete information.

With your current report, I can't make out:

* The platform
* The apt-offline version
