### ISSUE TITLE
List index out of range exception (Ubuntu 20.04)

### ISSUE THREAD

**Issue by kyp44** [rickysarraf/apt-offline#216]
### Error

On Ubuntu 20.04 I am getting the following Python error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/whitmdj/.install/apt-offline/apt_offline_core/AptOfflineLib.py", line 702, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/home/whitmdj/.install/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1291, in DataFetcher
    (url, pkgFile, download_size, checksum) = stripper(item)
  File "/home/whitmdj/.install/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 867, in stripper
    checksum = SplitItem[3].strip("'").strip()
IndexError: list index out of range
```

### Steps to reproduce

Generate an update signature file on the offline machine (Also Ubuntu 20.04):
```
sudo apt-offline set updates.sig --update
```
Move the signature to the online machine and run
```
apt-offline get updates.sig --bundle updates.zip
```
This command is what produces the above error.

### Other information
I am using the current latest commit (hash: `53bcd9c76e6dd5b100c708ad267d6e710e975937`) on both machines.

There is nothing odd about the signature file. I didn't want to paste the whole thing, but here are the first few lines:
```
'http://packages.microsoft.com/repos/code/dists/stable/InRelease' packages.microsoft.com_repos_code_dists_stable_InRelease 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/binary-amd64/Packages.xz' packages.microsoft.com_repos_code_dists_stable_main_binary-amd64_Packages 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/binary-arm64/Packages.xz' packages.microsoft.com_repos_code_dists_stable_main_binary-arm64_Packages 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/binary-armhf/Packages.xz' packages.microsoft.com_repos_code_dists_stable_main_binary-armhf_Packages 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/binary-all/Packages.xz' packages.microsoft.com_repos_code_dists_stable_main_binary-all_Packages 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/i18n/Translation-en_US.xz' packages.microsoft.com_repos_code_dists_stable_main_i18n_Translation-en%5fUS 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/i18n/Translation-en.xz' packages.microsoft.com_repos_code_dists_stable_main_i18n_Translation-en 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/dep11/Components-amd64.yml.xz' packages.microsoft.com_repos_code_dists_stable_main_dep11_Components-amd64.yml 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/dep11/Components-all.yml.xz' packages.microsoft.com_repos_code_dists_stable_main_dep11_Components-all.yml 0 
'http://packages.microsoft.com/repos/code/dists/stable/main/dep11/icons-48x48.tar.xz' packages.microsoft.com_repos_code_dists_stable_main_dep11_icons-48x48.tar 0 
```

In fact, I verified that this signature file, produced with the latest commit, is identical to that produced by the previous commit (hash: `b5cc3717454d32f261d07a6f55c578caeb6df3a3`), and that commit works just fine on the online side and does not produce the above exception.

**Comment by rickysarraf** [comment]
Dear @kyp44 

This some how slipped through my very limited tests. Thank you for reporting.

Could you please try https://github.com/rickysarraf/apt-offline/pull/217 ?

**Comment by rickysarraf** [comment]
> Sorry, only just now saw these updates. I may not be able to test the fix for a couple weeks as I use `apt-offline` at work and I am off for a couple of weeks.

No problem. I merged because it passed my tests, as well as I could reproduce and use it on a production machine. So I'm fairly confident it'll work for you as well.

**Comment by kyp44** [comment]
Just tested this and the fix worked for me. Thanks so much for fixing this quickly!
