### ISSUE TITLE
Exception in thread Thread-1 (run): IndexError: list index out of range 

### ISSUE THREAD

**Issue by pipatron** [rickysarraf/apt-offline#235]
I just got this exception with traceback but I don't really know how to debug it further on my side:

````
$ apt-offline get apt-offline.set -s /var/cache/apt/archives/ --bundle apt-offline-bundle.zip
````

````
http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/binary-all/Packages.xz done                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/i18n/Translation-en_US.xz                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/i18n/Translation-en.xz                                                             
http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/i18n/Translation-en.xz done                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/dep11/Components-amd64.yml.xz                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/dep11/Components-all.yml.xz                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/dep11/icons-48x48.tar.xz                                                             
Downloading http://ftp.se.debian.org/debian/dists/bookworm-updates/non-free/dep11/icons-64x64.tar.xz                                                             
Exception in thread Thread-1 (run):#############] 100.0% of 34 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 702, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1327, in DataFetcher
    if FetcherInstance.verifyPayloadIntegrity(full_file_path, checksum):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1131, in verifyPayloadIntegrity
    if self.CheckHashDigest(payload, checksum):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 115, in CheckHashDigest
    checksum = checksum.split( ":" )[1]
               ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
````

````
$ apt-offline --version
1.8.5
````

**Comment by rickysarraf** [comment]
Than you for the report. Could you please run the same with `--verbose` mode ? That should give some insight.
