### ISSUE TITLE
errors in debianbts - SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#30]
My hunch is that this happens with simultaneous connections to the BTS. But then, the exception rasied is: SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

Need to think on what will be the optimal handle for it.....

rrs@chutzpah:~/devel/apt-offline/apt-offline (master)$ ./apt-offline get /tmp/install.uris --threads 5 --cache-dir /var/cache/apt/archives/ --bundle /var/tmp/vbox.zip --bug-reports

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

Downloading libsmartcols1 2.27-1 - 112 KiB                               
Downloading mount 2.27-1 - 170 KiB                               
Fetched bug reports for package libseccomp2.                                                            
libseccomp2 copied from local cache directory /var/cache/apt/archives/.                              
Fetched bug reports for package libsmartcols1.                              
Fetched bug reports for package libapparmor1.                                                            
libsmartcols1 2.27-1 done.                                                            
libapparmor1 copied from local cache directory /var/cache/apt/archives/.                              
Fetched bug reports for package libsystemd0.                                                            
libsystemd0 copied from local cache directory /var/cache/apt/archives/.                              
Downloading libfdisk1 2.27-1 - 188 KiB                               
Fetched bug reports for package libfdisk1.                              
libfdisk1 2.27-1 done.                                                            
Downloading util-linux 2.27-1 - 876 KiB                               
Fetched bug reports for package libgcrypt20.                                                            
libgcrypt20 copied from local cache directory /var/cache/apt/archives/.                              
  7 /22Exception in thread Thread-3:           ]  35.9% of 5 MiB
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 632, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 636, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian(PackageName) in [1,2]:
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 166, in FetchBugsDebian
    bugReport = debianbts.get_bug_log(eachBug)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 235, in get_bug_log
    reply = server.get_bug_log(nr)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 545, in __call__
    return self.__r_call(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 567, in __r_call
    self.__hd, self.__ma)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 430, in __call
    timeout = self.timeout)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 244, in call
    r.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1273, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 632, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 765, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian( PackageName ) in [1, 2]:
  File "/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 166, in FetchBugsDebian
    bugReport = debianbts.get_bug_log(eachBug)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 235, in get_bug_log
    reply = server.get_bug_log(nr)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 545, in __call__
    return self.__r_call(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 567, in __r_call
    self.__hd, self.__ma)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 430, in __call
    timeout = self.timeout)
  File "/usr/lib/python2.7/dist-packages/SOAPpy/Client.py", line 244, in call
    r.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 1048, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 854, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1273, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

**Comment by rickysarraf** [comment]
So, with multiple people running into the same exception online, this is not something specific to apt-offline. It may be specific to Openssl in Deban, but that too is highly unlikely.

https://github.com/ipython/ipython/issues/7649
https://bugs.launchpad.net/ubuntu/+source/python-defaults/+bug/1363356


The interesting bit about these errors is that nobody has fixed it. :-)

So we'll keep this bug open, just because I don't want other users coming and filing a duplicate one.

**Comment by rickysarraf** [comment]
And this one has a better explanation: http://stackoverflow.com/questions/32330919/python-ssl-ssl-sslerror-ssl-unsupported-protocol-unsupported-protocol-ssl

**Comment by rickysarraf** [comment]
We can't ignore these bug reports. But at the same time we cannot fail the entire operation because of a bug report fail. IN latest ommit: 4deac068e2dfedb0d9628af9b2be0d00e5608469 this should now become a non-fatal error.
