### ISSUE TITLE
Exception in download

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#34]
This, IMO, is triggered on a congested network. It should be an intermittent corner case issue. Still, investigate the exception and handle it.

file 1%3a5.24-2 done.                                                            
Downloading gettext-base 0.19.6-1 - 119 KiB                               
 47 /12Exception in thread Thread-4:#          ]  68.3% of 108 MiB
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineLib.py", line 620, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 734, in DataFetcher
    if FetcherInstance.download_from_web( url, pkgFile, Str_DownloadDir ) == True:
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 250, in download_from_web
    temp = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1131, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

gettext-base 0.19.6-1 done.                                                            
libkeyutils1 copied from local cache directory /var/cache/apt/archives/.

**Comment by rickysarraf** [comment]
https://bugs.python.org/issue8823
