### ISSUE TITLE
another random exception

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#36]
`rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (master)$ apt-offline get /tmp/set.uris --threads 5 -d /var/tmp/data/.zip `

```
Fetching APT Data

ERROR: I couldn't create directory /var/tmp/data/.zip
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1984, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 510, in fetcher
    errfunc( 1, '' )
TypeError: errfunc() takes exactly 3 arguments (2 given)
2015-10-31 / 22:32:29 ♒♒♒    ☹  => 1  ```

**Comment by rickysarraf** [comment]
Fixed in 8cc8a610e516de148631a8e6ed705798d18643c0
