### ISSUE TITLE
bug during fetch debian bts

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#45]
Another bug found today. But this one doesn't look to be out problem. Possibly debianbts's problem.

```
Fetched bug reports for package libhogweed4                               
libhogweed4 3.1.1-4 done                                                             
Downloading python2.7 2.7.11-3 - 258 KiB                               
 34 / 122 itemsException in thread Thread-5:####]  99.9% of 31 MiB
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 636, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1097, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian( PackageName ) in [1, 2]:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 174, in FetchBugsDebian
    bugReport = debianbts.get_bug_log(eachBug)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 320, in get_bug_log
    reply = _soap_client_call('get_bug_log', nr)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 477, in _soap_client_call
    return getattr(soap_client, method_name)(soap_client, *soap_args)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 179, in <lambda>
    return lambda self=self, *args, **kwargs: self.call(attr, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 262, in call
    jetty=self.__soap_server in ('jetty',))
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/simplexml.py", line 56, in __init__
    self.__document = xml.dom.minidom.parseString(text)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: syntax error: line 1, column 49

```

**Comment by rickysarraf** [comment]
And I got this one again, today, so this too needs investigation:

```
adduser copied from local cache directory /var/cache/apt/archives/                             Downloading bootlogd 2.88dsf-59.4 - 58 KiB                               
 28No handlers could be found for logger "pysimplesoap.simplexml"B
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 636, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1072, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian(PackageName) in [1,2]:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 174, in FetchBugsDebian
    bugReport = debianbts.get_bug_log(eachBug)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 320, in get_bug_log
    reply = _soap_client_call('get_bug_log', nr)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 477, in _soap_client_call
    return getattr(soap_client, method_name)(soap_client, *soap_args)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 179, in <lambda>
    return lambda self=self, *args, **kwargs: self.call(attr, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 262, in call
    jetty=self.__soap_server in ('jetty',))
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/simplexml.py", line 56, in __init__
    self.__document = xml.dom.minidom.parseString(text)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: syntax error: line 1, column 49

Fetched bug reports for package insserv                                                        
```

**Comment by rickysarraf** [comment]
Another one today.

```
python3 copied from local cache directory /var/cache/apt/archives/                             Fetched bug reports for package libpython3.5-stdlib                                                             
libpython3.5-stdlib copied from local cache directory /var/cache/apt/archives/                               No handlers could be found for logger "pysimplesoap.simplexml"
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 642, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1071, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian(PackageName) in [1,2]:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 172, in FetchBugsDebian
    bugReport = debianbts.get_bug_log(eachBug)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 320, in get_bug_log
    reply = _soap_client_call('get_bug_log', nr)
  File "/usr/lib/python2.7/dist-packages/debianbts.py", line 477, in _soap_client_call
    return getattr(soap_client, method_name)(soap_client, *soap_args)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 179, in <lambda>
    return lambda self=self, *args, **kwargs: self.call(attr, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/client.py", line 262, in call
    jetty=self.__soap_server in ('jetty',))
  File "/usr/lib/python2.7/dist-packages/pysimplesoap/simplexml.py", line 56, in __init__
    self.__document = xml.dom.minidom.parseString(text)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
ExpatError: syntax error: line 1, column 49

Fetched bug reports for package python3.5                                                             
python3.5 copied from local cache directory /var/cache/apt/archives/                           Fetched bug reports for package libpython3-stdlib                                                             
libpython3-stdlib copied from local cache directory /var/cache/apt/archives/                   Fetched bug reports for package acl                                                            
```

**Comment by rickysarraf** [comment]
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801585

**Comment by rickysarraf** [comment]
These are foreign (debianbts) bugs. And have been reported to the developers. Hence, closing here.
