### ISSUE TITLE
zipfile exception on hurd platform

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#47]
rrs@learner:~$ cat apt-offline-hurd-bug.txt 
debianutils_4.7_hurd-i386.deb file synced.
libuuid1_2.27.1-3_hurd-i386.deb file synced.
gnumach-dev_2%3a1.6+git20160114-1_hurd-i386.deb file synced.
libblkid1_2.27.1-3_hurd-i386.deb file synced.
libp11-kit0_0.23.1-3_hurd-i386.deb file synced.
libc-dev-bin_2.21-7_hurd-i386.deb file synced.
libc-bin_2.21-7_hurd-i386.deb file synced.
hurd-libs0.3_1%3a0.7.git20160114-1_hurd-i386.deb file synced.
init-system-helpers_1.28_all.deb file synced.
sysvinit-utils_2.88dsf-59.3_hurd-i386.deb file synced.
bash_4.3-14+b1_hurd-i386.deb file synced.
sysv-rc_2.88dsf-59.3_all.deb file synced.
insserv_1.14.0-5.2_hurd-i386.deb file synced.
initscripts_2.88dsf-59.3_hurd-i386.deb file synced.
libc0.3-dev_2.21-7_hurd-i386.deb file synced.
libparted2_3.2-14_hurd-i386.deb file synced.
libsub-name-perl_0.14-1+b1_hurd-i386.deb file synced.
libc0.3_2.21-7_hurd-i386.deb file synced.
libxml-libxml-perl_2.0123+dfsg-1+b1_hurd-i386.deb file synced.
hurd_1%3a0.7.git20160114-1_hurd-i386.deb file synced.
perl_5.22.1-1_hurd-i386.deb file synced.
hurd-dev_1%3a0.7.git20160114-1_hurd-i386.deb file synced.
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1997, in main
    args.func(args)
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1368, in installer
    data.file.write( zipBugFile.read( filename ) )
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 630, in read
    data = self.read1(n)
  File "/usr/lib/python2.7/zipfile.py", line 684, in read1
    max(n - len_readbuffer, self.MIN_READ_SIZE)
zlib.error: Error -3 while decompressing: invalid block type
2016-02-09 / 00:33:02 ♒♒♒  ☺

**Comment by rickysarraf** [comment]
This one was seen on the Hurd. As per Hurd dev Samuel, GNU/Hurd still has memory issues. This seems to be only seen on Hurd with the dataset because the same, when run on Linux, is non-existent.

We need to be more resilient to such errors. Instead of bailing out on first occurrence of the error, hold it off till the end.

**Comment by rickysarraf** [comment]
Note: This is an odd exception only seen when running Hurd on kvm under libvirt. THe same dataset, when run under vbox (with kvm hypervisor), was perfectly fine.

**Comment by rickysarraf** [comment]
This was an odd hurd memory problem. For such a corner case, there's no point in handling it in the application unless there are many users coming complaining.
