### ISSUE TITLE
CacheDir gets set to None and writeToCache blows up

### ISSUE THREAD

**Issue by Fuzion24** [rickysarraf/apt-offline#53]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineLib.py", line 669, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1201, in DataFetcher
    FetcherInstance.writeToCache(pkgFile)
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1020, in writeToCache
    self.copy_file(data, self.CacheDir)
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineLib.py", line 552, in copy_file
    destFile = os.path.join(dest, os.path.basename(src))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by Fuzion24** [comment]
https://github.com/rickysarraf/apt-offline/blob/master/apt_offline_core/AptOfflineCoreLib.py#L1016

Maybe you want this?
```python
if self.CacheDir is not False:
```
to 
```python
if self.CacheDir is not None:
```

**Comment by copyninja** [comment]
Following should be correct , it is true when something is not None or True

``python
if self.CacheDir
```

**Comment by rickysarraf** [comment]
@Fuzion24 Could you please share the console output? I'm curious what combination of the options trigger the bug.

**Comment by Fuzion24** [comment]
I believe I was hitting this just passing `apt-offline get <sig> --bundle` `

**Comment by rickysarraf** [comment]
Thank you. Am able to reproduce now.

```
rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (master)$ ./apt-offline get /var/tmp/bugreports.uris --bundle /var/tmp/foo.zip 

Fetching APT Data

Downloading libc6-dev - 2 MiB                                                             
libc6-dev done                                                             
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 669, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1198, in DataFetcher
    FetcherInstance.writeToCache(pkgFile)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1017, in writeToCache
    self.copy_file(data, self.CacheDir)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 552, in copy_file
    destFile = os.path.join(dest, os.path.basename(src))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'


Downloaded data to /var/tmp/foo.zip
2016-07-04 / 12:04:11 ♒♒♒  ☺  
```
