### ISSUE TITLE
py3 port exception

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#63]
```
WARN: Will still try with other package uris
Exception ignored in: <_io.FileIO name='deb.debian.org_debian_dists_testing_main_binary-all_Packages' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='deb.debian.org_debian_dists_testing_main_binary-all_Packages'>
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 691, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1297, in DataFetcher
    if DownloadPackages(NewUrl) is True:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1259, in DownloadPackages
    if FetcherInstance.download_from_web(url, pkgFile, Str_DownloadDir):
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 709, in download_from_web
    temp = urllib.request.urlopen(url)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

ERROR: Socket timeout. Skipping URL: http://deb.debian.org/debian/dists/testing/main/binary-all/Packages.bz2
```

**Comment by rickysarraf** [comment]
```
ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.7', 50994), raddr=('209.87.16.39', 443)>
WARN: http://deb.debian.org/debian/pool/main/q/qemu/qemu-system-misc_2.8+dfsg-5+b1_amd64.deb - 101010 - Max timeout retry count reached. Discontinuing download.
                                                             
WARN: Will still try with other package uris
Exception ignored in: <_io.FileIO name='qemu-system-misc_1%3a2.8+dfsg-5+b1_amd64.deb' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='qemu-system-misc_1%3a2.8+dfsg-5+b1_amd64.deb'>
Downloading qemu-system-ppc - 6 MiB                                                             
Exception ignored in: <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.7', 50996), raddr=('209.87.16.39', 443)>
ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('192.168.1.7', 50996), raddr=('209.87.16.39', 443)>
```

Here's what I think must be happening.
* Connection established to a URL.
* local file descriptor opened
* some data fetched.
* later socket timed out and raised an exception
* file descriptor got left open because of the exception

**Comment by rickysarraf** [comment]
This issue hasn't been seen in a while now.
