### ISSUE TITLE
ImportError: No module named 'resources_rc'

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#66]
So the problem is that the package module's path is not in the list. Need to find the optimal way to handle this. appending sys.path is something I'd like to avoid.

```
rrs@learner:/var/tmp/Debian-Build/Result$ apt-offline-gui 
Traceback (most recent call last):
  File "/usr/bin/apt-offline-gui", line 30, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/lib/python3/dist-packages/apt_offline_gui/AptOfflineQtMain.py", line 4, in <module>
    from apt_offline_gui.Ui_AptOfflineQtMain import Ui_AptOfflineMain
  File "/usr/lib/python3/dist-packages/apt_offline_gui/Ui_AptOfflineQtMain.py", line 155, in <module>
    import resources_rc
ImportError: No module named 'resources_rc'
2017-05-23 / 12:07:13 ♒♒♒  ☹  => 1  
```

**Comment by rickysarraf** [comment]
Fixed with v1.8.1
