### ISSUE TITLE
jessie: failing on chunked transfers

### ISSUE THREAD

**Issue by magthe** [rickysarraf/apt-offline#67]
I'm using `apt-offline` against <http://snapshot.debian.org/> and it seems that it sometimes decides to send files with `Transfer-Encoding: chunked` which makes `apt-offline` error out with:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineLib.py", line 624, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 821, in DataFetcher
    if DownloadPackages(url) is False and guiTerminateSignal is False:
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 796, in DownloadPackages
    if FetcherInstance.download_from_web(url, pkgFile, Str_DownloadDir) == True:
  File "/usr/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 251, in download_from_web
    size = int(headers['Content-Length'])
  File "/usr/lib/python2.7/rfc822.py", line 388, in __getitem__
    return self.dict[name.lower()]
KeyError: 'content-length'
```

For the time being I'm stuck on Jessie (so using version 1.5). Unfortunately I can't test on Stretch at the moment, but a quick look in the code suggests that not much has changed in `GenericDownloadFunction.download_from_web` so it's likely an issue in newer versions as well.

**Comment by rickysarraf** [comment]
Can you please share the signature file from the set operation? I'd like to
reproduce this locally.

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by magthe** [comment]
Here's a signature file that `snapshot get` fails on:

[snapshot.txt](https://github.com/rickysarraf/apt-offline/files/1118141/snapshot.txt)

**Comment by rickysarraf** [comment]
Thanks. I can see the problem locally. I'll see what best can be done for this case.
