### ISSUE TITLE
routing batch testing on windows uncovered this bug

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#7]
Downloading libecj-java 3.9.0-2 - 1 MiB
http://ftp.debian.org/debian/dists/unstable/main/binary-amd64/Packages.gz done.

Downloading libcommons-pool-java 1.6-2 - 103 KiB
Exception in thread Thread-3:##################]  99.0% of 67 MiB
Traceback (most recent call last):
  File "C:\Users\rsarraf\AppData\Local\Continuum\Miniconda\lib\threading.py", li
ne 810, in __bootstrap_inner
    self.run()
  File "C:\Users\rsarraf\AppData\Local\Continuum\Miniconda\lib\threading.py", li
ne 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "H:\apt-offline\apt_offline_core\AptOfflineLib.py", line 601, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "H:\apt-offline\apt_offline_core\AptOfflineCoreLib.py", line 752, in Data
Fetcher
    if FetchBugReportsDebian.FetchBugsDebian( PackageName ) in [1, 2]:
  File "H:\apt-offline\apt_offline_core\AptOfflineCoreLib.py", line 147, in Fetc
hBugsDebian
    except NoNetwork:
NameError: global name 'NoNetwork' is not defined

ant-optional 1.9.4-1 done.

Downloading libcommons-dbcp-java 1.4-4 - 151 KiB
http://ftp.debian.org/debian/dists/unstable/main/binary-i386/Packages.gz done.

Downloading libservlet3.0-java 7.0.53-1 - 304 KiB

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\rsarraf\AppData\Local\Continuum\Miniconda\lib\threading.py", li
ne 810, in __bootstrap_inner
    self.run()
  File "C:\Users\rsarraf\AppData\Local\Continuum\Miniconda\lib\threading.py", li
ne 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "H:\apt-offline\apt_offline_core\AptOfflineLib.py", line 601, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "H:\apt-offline\apt_offline_core\AptOfflineCoreLib.py", line 752, in Data
Fetcher
    if FetchBugReportsDebian.FetchBugsDebian( PackageName ) in [1, 2]:
  File "H:\apt-offline\apt_offline_core\AptOfflineCoreLib.py", line 147, in Fetc
hBugsDebian
    except NoNetwork:
NameError: global name 'NoNetwork' is not defined

ant 1.9.4-1 done.
Downloading libtomcat7-java 7.0.53-1 - 3 MiB
libcommons-dbcp-java 1.4-4 done.

**Comment by rickysarraf** [comment]
This seems to have been fixed some time ago.
