### ISSUE TITLE
subprocess TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#74]
```
sid-container:~/apt-offline# ./apt-offline install ../update.zip --verbose
VERBOSE: Namespace(allow_unauthenticated=False, func=<function installer at 0x7f614fee0ea0>, install='../update.zip', install_src_path=None, simulate=False, skip_bug_reports=False, skip_changelog=False, verbose=True)
No changelog available
(Y) Yes. Proceed with installation
(N) No, Abort.
(C) Display changelog
(?) Display this help message.
What would you like to do next:	 (y, N, ?)y
Proceeding with installation
VERBOSE: {}
VERBOSE: Great!!! No bugs found for all the packages that were downloaded.

VERBOSE: File is httpredir.debian.org_debian_dists_sid_Release.gpg, hence 'True'.
VERBOSE: httpredir.debian.org_debian_dists_sid_Release.gpg file synced to APT.
VERBOSE: httpredir.debian.org_debian_dists_sid_InRelease file synced to APT.
VERBOSE: httpredir.debian.org_debian_dists_sid_Release file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_binary-amd64_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_binary-amd64_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_binary-amd64_Packages file synced to APT.
Hello

Traceback (most recent call last):
  File "./apt-offline", line 28, in <module>
    main()
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 2212, in main
    args.func(args)
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1918, in installer
    AptSecure = APTVerifySigs(Simulate=InstallerInstance.Bool_TestWindows)
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 594, in __init__
    output = process.communicate(input=command)[0]
  File "/usr/lib/python3.5/subprocess.py", line 803, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1441, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
sid-container:~/apt-offline# 
```

**Comment by rickysarraf** [comment]
This error is only seen when invoking subprocess.

```
root@sid-container:~# apt-offline  install container-update.zip 
No changelog available
(Y) Yes. Proceed with installation
(N) No, Abort.
(C) Display changelog
(?) Display this help message.
What would you like to do next:	 (y, N, ?)y
Proceeding with installation
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2211, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1917, in installer
    AptSecure = APTVerifySigs(Simulate=InstallerInstance.Bool_TestWindows)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 594, in __init__
    output = process.communicate(input=command)[0]
  File "/usr/lib/python3.5/subprocess.py", line 803, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1441, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
root@sid-container:~# apt policy python-apt
python-apt:
  Installed: 1.4.0~beta3+b1
  Candidate: 1.4.0~beta3+b1
  Version table:
 *** 1.4.0~beta3+b1 990
        990 http://httpredir.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
root@sid-container:~# apt policy python3-apt
python3-apt:
  Installed: (none)
  Candidate: 1.4.0~beta3+b1
  Version table:
     1.4.0~beta3+b1 990
        990 http://httpredir.debian.org/debian sid/main amd64 Packages
root@sid-container:~# apt install python3-apt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  python3-apt-dbg python-apt-doc
Recommended packages:
  lsb-release iso-codes
The following NEW packages will be installed:
  python3-apt
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 171 kB of archives.
After this operation, 1032 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian sid/main amd64 python3-apt amd64 1.4.0~beta3+b1 [171 kB]
Fetched 171 kB in 2s (82.7 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package python3-apt.
(Reading database ... 11015 files and directories currently installed.)
Preparing to unpack .../python3-apt_1.4.0~beta3+b1_amd64.deb ...
Unpacking python3-apt (1.4.0~beta3+b1) ...
Setting up python3-apt (1.4.0~beta3+b1) ...
root@sid-container:~# apt-offline  install container-update.zip 
No changelog available
(Y) Yes. Proceed with installation
(N) No, Abort.
(C) Display changelog
(?) Display this help message.
What would you like to do next:	 (y, N, ?)y
Proceeding with installation
ERROR: Path for keyring is invalid: /etc/apt/trusted.gpg
gpgv: Signature made Sun Jan  7 09:17:49 2018 IST
gpgv:                using RSA key A1BD8E9D78F7FE5C3E65D8AF8B48AD6246925553
gpgv: Good signature from "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>"
gpgv: Signature made Sun Jan  7 09:17:49 2018 IST
gpgv:                using RSA key 126C0D24BD8A2942CC7DF8AC7638D0442B90D010
gpgv: Good signature from "Debian Archive Automatic Signing Key (8/jessie) <ftpmaster@debian.org>"
httpredir.debian.org_debian_dists_sid_InRelease synced.
httpredir.debian.org_debian_dists_sid_Release synced.
httpredir.debian.org_debian_dists_sid_Release.gpg synced.
httpredir.debian.org_debian_dists_sid_contrib_binary-all_Packages synced.
httpredir.debian.org_debian_dists_sid_contrib_binary-amd64_Packages synced.
httpredir.debian.org_debian_dists_sid_contrib_i18n_Translation-en synced.
httpredir.debian.org_debian_dists_sid_main_binary-all_Packages synced.
httpredir.debian.org_debian_dists_sid_main_binary-amd64_Packages synced.
httpredir.debian.org_debian_dists_sid_non-free_binary-all_Packages synced.
httpredir.debian.org_debian_dists_sid_non-free_binary-amd64_Packages synced.
httpredir.debian.org_debian_dists_sid_non-free_i18n_Translation-en synced.
root@sid-container:~# 
```

**Comment by Patryk27** [comment]
Hi,

I stumbled upon this problem yesterday (in the newest 1.8.1 version on Kubuntu 19.04) and I prepared a simple fix that seems to work (https://github.com/Patryk27/apt-offline/commit/925d910536dc8b4e503423dd8b807364e8576022) - could you please take a look and see if that could be merged upstream?

I'm not a Python programmer, so if anything can be done better (or if the problem itself lays somewhere else), let me know.

Thanks! :-)

**Comment by rickysarraf** [comment]
@Patryk27 Thank you for the patch. The changes look fine and the issue is not seen with the patch. Merged.
