### ISSUE TITLE
UnboundLocalError: local variable 'raw_data_list' referenced before assignment

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#77]
Should bail out.

```
rrs@priyasi:/usr/local/stow/libinput-gestures$ apt-offline get /var/tmp/lio.uris --threads 5 --cache-dir /var/cache/apt/archives/ --bundle /var/tmp/lio.zip 

Fetching APT Data

ERROR: 13 Permission denied
WARN: /var/tmp/lio.uris - 13 -                                                              
WARN: Will still try with other package uris
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2211, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1126, in fetcher
    for item in raw_data_list:
UnboundLocalError: local variable 'raw_data_list' referenced before assignment
10:14 ♒♒♒    ☹  => 1  
```

**Comment by rickysarraf** [comment]
Closes with: 8eac63ccb06d87fb0e174d1d1b7236809e95db88
